<a href="https://colab.research.google.com/github/Shrideshi1/multi-label-email-risk-detection/blob/main/notebooks/03_model_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##Import libraries
import os
import joblib
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split
from google.colab import drive
##Models
from sklearn.linear_model import LogisticRegression
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline
##Metrics and Processing
from sklearn.metrics import classification_report, hamming_loss, accuracy_score, precision_score, recall_score, f1_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import hamming_loss, f1_score, precision_score, recall_score
from scipy.sparse import hstack, csr_matrix
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV

In [ ]:
drive.mount("/content/drive")

PROJECT_DIR = "/content/drive/.shortcut-targets-by-id/1SLhiH7VulyiPZ7L846kJBEbN1pa4c4zU/Multi_Label_Email_Risk_Detection/"
DATA_RAW_DIR = f"{PROJECT_DIR}/data/raw"
DATA_PROCESSED_DIR = f"{PROJECT_DIR}/data/processed"
MODELS_DIR = f"{PROJECT_DIR}/models"
REPORTS_DIR = f"{PROJECT_DIR}/reports"
FEATURE_DIR = f"{PROJECT_DIR}/data/processed/features"
os.chdir(PROJECT_DIR)

print("Current folder:", os.getcwd())
print("Processed files:", os.listdir(DATA_PROCESSED_DIR))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Current folder: /content/drive/.shortcut-targets-by-id/1SLhiH7VulyiPZ7L846kJBEbN1pa4c4zU/Multi_Label_Email_Risk_Detection
Processed files: ['combined_dataset.csv', 'features', 'synthetic_confidential.csv']

In [ ]:

combined_df = pd.read_csv(f"{DATA_PROCESSED_DIR}/combined_dataset.csv")

risk_cols = [
    "financial_risk",
    "credential_risk",
    "customer_info_risk",
    "proprietary_risk",
    "legal_risk",
    "attachment_risk",
    "phishing_spam_risk"
]

print("Dataset shape:", combined_df.shape)
display(combined_df.head())

Dataset shape: (69910, 12)

,text,category,source,financial_risk,credential_risk,customer_info_risk,proprietary_risk,legal_risk,attachment_risk,phishing_spam_risk,project_category,risk_score
0,job posting - apple-iss research center conten...,ham,messages,0,0,0,0,0,0,0,Ham,0
1,"lang classification grimes , joseph e . and b...",ham,messages,0,0,0,0,0,0,0,Ham,0
2,query : letter frequencies for text identifica...,ham,messages,0,0,0,0,0,0,0,Ham,0
3,risk a colleague and i are researching the dif...,ham,messages,0,0,0,0,0,0,0,Ham,0
4,request book information earlier this morning ...,ham,messages,0,0,0,0,0,0,0,Ham,0

In [ ]:
#FEATURE_DIR = f"{PROJECT_DIR}/data/processed/features"

print(os.listdir(FEATURE_DIR))

['X_features.pkl', 'metadata_features.csv', 'y_labels.pkl', 'rule_features.csv', 'X_train_features.pkl', 'X_test_features.pkl', 'metadata_scaler.pkl', 'tfidf_vectorizer.pkl', 'y_test.pkl', 'y_train.pkl']

In [ ]:
# ------------------------------------------------------------
# Load Final Feature Engineering Outputs
# ------------------------------------------------------------




# Load feature matrices created in feature engineering notebook

X_train = joblib.load(
    f"{FEATURE_DIR}/X_train_features.pkl"
)

X_test = joblib.load(
    f"{FEATURE_DIR}/X_test_features.pkl"
)


# Load multi-label targets

Y_train = joblib.load(
    f"{FEATURE_DIR}/y_train.pkl"
)

Y_test = joblib.load(
    f"{FEATURE_DIR}/y_test.pkl"
)


# Dictionary for storing model results

results = {}


# Verify dimensions

print("Training feature shape:", X_train.shape)
print("Testing feature shape:", X_test.shape)

print("Training labels:", Y_train.shape)
print("Testing labels:", Y_test.shape)

Training feature shape: (55928, 10013)
Testing feature shape: (13982, 10013)
Training labels: (55928, 7)
Testing labels: (13982, 7)

####Logistic Model
$$z_k =w_k^T x + b_k$$

$$ P(y_k = 1| x) = σ(z_k) = \frac{1}{1+e^{-zk}}$$

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.multioutput import MultiOutputClassifier

# Define potential hyperparameters to test
param_grid_log = {
    "estimator__C": [10, 100, 500, 1000],
    "estimator__penalty": ["l1", "l2"],
    "estimator__solver": ["liblinear"]
}

# Initialize the multi-label Logistic Regression model
log_model = MultiOutputClassifier(
    LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=26
    )
)

# Perform grid search
log_search = GridSearchCV(
    estimator=log_model,
    param_grid=param_grid_log,
    cv=3,
    scoring="f1_weighted",
    n_jobs=-1,
    verbose=1
)

# Fit the model
log_search.fit(X_train, Y_train)

# Print the best results
print("Best Parameters:", log_search.best_params_)
print("Best Cross-Validation Weighted F1:", log_search.best_score_)

Fitting 3 folds for each of 8 candidates, totalling 24 fits
Best Parameters: {'estimator__C': 1000, 'estimator__penalty': 'l2', 'estimator__solver': 'liblinear'}
Best Cross-Validation Weighted F1: 0.9891924682028934

In [ ]:
##Logistic Model


log_model = MultiOutputClassifier(LogisticRegression(C=1000, penalty= 'l2', solver='liblinear', max_iter=1000, class_weight="balanced"))
##+ C 1000 | + penlty 'l2' | + solver 'lbfgs

##Train Model
log_model.fit(X_train, Y_train)

##Make Predications
log_preds = log_model.predict(X_test)
log_probs = log_model.predict_proba(X_test)
##Get Metrics
acc = accuracy_score(Y_test, log_preds)
prec = precision_score(Y_test, log_preds, average='weighted', zero_division=0)
rec = recall_score(Y_test, log_preds, average='weighted', zero_division=0)
f1 = f1_score(Y_test, log_preds, average='weighted', zero_division=0)
hl = hamming_loss(Y_test, log_preds)

##Store Metrics For comparision later
results['LogisticRegression'] = {'accuracy': acc, 'precision': prec, 'recall': rec, 'f1': f1,'hamming_loss': hl }
##Print here for Claritry/Checks
print(f"Metrics for Logistic Regression:")
print(f"Accuracy: {acc}, Precision: {prec}, Recall: {rec}, F1: {f1},Hamming Loss: {hl}")

#Save the model
os.makedirs(MODELS_DIR, exist_ok=True)

joblib.dump(
    log_model,
    f"{MODELS_DIR}/logistic_regression_model.pkl"
)

# Save the predictions
joblib.dump(
    log_preds,
    f"{REPORTS_DIR}/logistic_regression_predictions.pkl"
)

Metrics for Logistic Regression:
Accuracy: 0.9875554284079531, Precision: 0.9895105657750091, Recall: 0.9912758996728462, F1: 0.9903735597264091,Hamming Loss: 0.002155833009788095

['/content/drive/.shortcut-targets-by-id/1SLhiH7VulyiPZ7L846kJBEbN1pa4c4zU/Multi_Label_Email_Risk_Detection//reports/logistic_regression_predictions.pkl']

##Random Forest
Decision Tree Node (Gini Index)-
$$G = 1 - \sum_{k=1}^{K}\hat p_{mk}(1-\hat p_{mk})$$

Forest Level Probability Across Trees-

$$\hat{p_k} = \frac{1}{N}\sum_{n=1}^{N}T_n(x)_k$$

In [ ]:
##Random Forest Model
RFor_model = MultiOutputClassifier(RandomForestClassifier(n_estimators=200, max_depth=None, max_features='sqrt', random_state=26))
##n-est 100-> 200 | max-dpt 10 -> None | + max_features 'sqrt'

##Train Model
RFor_model.fit(X_train, Y_train)

##Make predictions
RFor_preds = RFor_model.predict(X_test)

##Get Metrics
acc = accuracy_score(Y_test, RFor_preds)
prec = precision_score(Y_test, RFor_preds, average='weighted', zero_division=0)
rec = recall_score(Y_test, RFor_preds, average='weighted', zero_division=0)
f1 = f1_score(Y_test, RFor_preds, average='weighted', zero_division=0)
hl = hamming_loss(Y_test, RFor_preds)

##Store Metrics
results['RandomForest'] = {'accuracy': acc, 'precision': prec, 'recall': rec, 'f1': f1,'hamming_loss': hl}

print(f"Metrics for Random Forest:")
print(f"Accuracy: {acc}, Precision: {prec}, Recall: {rec}, F1: {f1},Hamming Loss: {hl}")

# Save the model
os.makedirs(MODELS_DIR, exist_ok=True)

joblib.dump(
    RFor_model,
    f"{MODELS_DIR}/random_forest_model.pkl"
)

# Save the predictions
joblib.dump(
    RFor_preds,
    f"{REPORTS_DIR}/random_forest_predictions.pkl"
)

Metrics for Random Forest:
Accuracy: 0.9895580031469031, Precision: 0.9977850593389195, Recall: 0.9880043620501636, F1: 0.9928218055456276,Hamming Loss: 0.0015938860167153688

['/content/drive/.shortcut-targets-by-id/1SLhiH7VulyiPZ7L846kJBEbN1pa4c4zU/Multi_Label_Email_Risk_Detection//reports/random_forest_predictions.pkl']

In [ ]:
# Reduced hyperparameter search space.
param_grid = {
    "estimator__n_estimators": [100, 200],
    "estimator__max_depth": [10, 20]
}

# Randomized hyperparameter search.
rf_search = RandomizedSearchCV(
    MultiOutputClassifier(
        RandomForestClassifier(
            random_state=26,
            n_jobs=-1
        )
    ),
    param_distributions=param_grid,
    n_iter=3,          # Evaluate 3 parameter combinations.
    cv=2,              # 2-fold cross-validation.
    scoring="f1_weighted",
    n_jobs=-1,
    verbose=1,
    random_state=26
)

# Train search.
rf_search.fit(X_train, Y_train)

# Best configuration.
print("Best Parameters:", rf_search.best_params_)
print("Best Score:", rf_search.best_score_)

Fitting 2 folds for each of 3 candidates, totalling 6 fits
Best Parameters: {'estimator__n_estimators': 100, 'estimator__max_depth': 20}
Best Score: 0.9309384149750766

####Gradient Boosting (XGBoost)
$$\hat{f}(x) = \sum_{t=1}^{D}λ \hat f^t(x)$$

$\hat f^t$ - Decsion Tree  @ t

$x$ - Input

#####Minimize Loss Function
$$ \text{Loss}^{(t)} = \sum_{i=1}^{n} L(y_i, \hat{y}_i^{(t-1)} + λ \hat f^t(x_i)) + \Omega(\hat f^t)$$

$ L $ - Log-loss

$ y_i $ - Ground Truth

$ \hat{y}_i^{(t-1)} $ - Current Prediction

$λ$ - Learning Rate

$\hat f^t(x_i)$ - New Tree

$ \Omega(\hat f^t) $ -Regularization term (Prevent Overfitting)

In [ ]:
##Gradient Boosting (XGBoost)
X_model = MultiOutputClassifier(XGBClassifier(
  n_estimators=100,  ##100 Trees
  learning_rate=0.1,
  max_depth=6,  ##Regularization set at 6
  tree_method='hist',
  n_jobs=-1,
  eval_metric='logloss'))
##Train Model
X_model.fit(X_train, Y_train, verbose=True)
##Make Predictions
X_preds = X_model.predict(X_test)
##Get Metrics
acc = accuracy_score(Y_test, X_preds)
prec = precision_score(Y_test, X_preds, average='weighted', zero_division=0)
rec = recall_score(Y_test, X_preds, average='weighted', zero_division=0)
f1 = f1_score(Y_test, X_preds, average='weighted', zero_division=0)
hl = float(hamming_loss(Y_test, X_preds))
micro_f1 = f1_score(Y_test, X_preds, average='micro')
macro_f1 = f1_score(Y_test, X_preds, average='macro')

##Store Metrics
results['XGBoost'] = {'subset_accuracy': acc, 'precision': prec, 'recall': rec, 'f1': f1,'hamming_loss': hl, 'micro_f1':micro_f1, 'macro_f1':macro_f1 }

print(f"Metrics for XGBoost:")
print(f"Accuracy: {acc}, Precision: {prec}, Recall: {rec}, F1: {f1}, Hamming Loss: {hl}, 'micro_f1': {micro_f1}, 'macro_f1': {macro_f1}")

# Save the model
os.makedirs(MODELS_DIR, exist_ok=True)

joblib.dump(
    X_model,
    f"{MODELS_DIR}/xgboost_model.pkl"
)

# Save the predictions
joblib.dump(
    X_preds,
    f"{REPORTS_DIR}/xgboost_predictions.pkl"
)

Metrics for XGBoost:
Accuracy: 0.9846946073523101, Precision: 0.992838548425731, Recall: 0.9861868411486732, F1: 0.9894711866221833, Hamming Loss: 0.0023499601528495823, 'micro_f1': 0.9895139965350597, 'macro_f1': 0.9909444263817286

['/content/drive/.shortcut-targets-by-id/1SLhiH7VulyiPZ7L846kJBEbN1pa4c4zU/Multi_Label_Email_Risk_Detection//reports/xgboost_predictions.pkl']

####Support Vector Machines
$$ f_k(x) = w_k^T x+b_k $$

$ w_k^T $ - Weight Vector for Class k

$ b_k $ Bias for class k

In [ ]:
#Support Vector Machines
from sklearn.linear_model import SGDClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.calibration import CalibratedClassifierCV

SVM_model = MultiOutputClassifier(
    CalibratedClassifierCV(
        SGDClassifier(
            loss='hinge',
            penalty='l2',
            alpha=0.001,
            class_weight='balanced',
            random_state=42,
            n_jobs=-1
        ),
        method='sigmoid',
        cv=5
    )
)


##Train and Predict
SVM_model.fit(X_train, Y_train)
SVM_preds = SVM_model.predict(X_test)


##Overall Evaluation Metrics
acc = accuracy_score(Y_test, SVM_preds)
prec = precision_score(Y_test, SVM_preds, average='weighted', zero_division=0)
rec = recall_score(Y_test, SVM_preds, average='weighted', zero_division=0)
f1 = f1_score(Y_test, SVM_preds, average='weighted', zero_division=0)
hl = hamming_loss(Y_test, SVM_preds)
micro_f1 = f1_score(Y_test, SVM_preds, average='micro')
macro_f1 = f1_score(Y_test, SVM_preds, average='macro')


##Print Metrics for Each Risk Category
for i, col in enumerate(risk_cols):
    print(f"\n{col}")
    print(classification_report(Y_test.iloc[:, i], SVM_preds[:, i], zero_division=0))


##Store and Display Results
results["SVM"] = {"accuracy": acc, "precision": prec, "recall": rec, "f1": f1, 'hamming_loss': hl,"micro_f1": micro_f1, "macro_f1": macro_f1}


print("\nMetrics for SVM:")
print(f"Accuracy: {acc:.4f}, Precision: {prec:.4f}, Recall: {rec:.4f}, F1 Score: {f1:.4f}, Hamming Loss: {hl:.4f}, Micro F1: {micro_f1:.4f}, Macro F1: {macro_f1:.4f}")


# Save the model
os.makedirs(MODELS_DIR, exist_ok=True)

joblib.dump(
    SVM_model,
    f"{MODELS_DIR}/svm_model.pkl"
)

# Save the predictions
joblib.dump(
    SVM_preds,
    f"{REPORTS_DIR}/svm_predictions.pkl"
)

financial_risk
              precision    recall  f1-score   support

           0       0.99      1.00      0.99     13179
           1       0.94      0.82      0.88       803

    accuracy                           0.99     13982
   macro avg       0.96      0.91      0.93     13982
weighted avg       0.99      0.99      0.99     13982


credential_risk
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     13624
           1       1.00      1.00      1.00       358

    accuracy                           1.00     13982
   macro avg       1.00      1.00      1.00     13982
weighted avg       1.00      1.00      1.00     13982


customer_info_risk
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     13622
           1       0.99      1.00      0.99       360

    accuracy                           1.00     13982
   macro avg       0.99      1.00      1.00     13982
weighted avg       1.00      1.00      1.00     13982


proprietary_risk
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     13786
           1       0.99      1.00      1.00       196

    accuracy                           1.00     13982
   macro avg       1.00      1.00      1.00     13982
weighted avg       1.00      1.00      1.00     13982


legal_risk
              precision    recall  f1-score   support

           0       1.00      0.99      0.99      9713
           1       0.98      0.99      0.99      4269

    accuracy                           0.99     13982
   macro avg       0.99      0.99      0.99     13982
weighted avg       0.99      0.99      0.99     13982


attachment_risk
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     13644
           1       1.00      1.00      1.00       338

    accuracy                           1.00     13982
   macro avg       1.00      1.00      1.00     13982
weighted avg       1.00      1.00      1.00     13982


phishing_spam_risk
              precision    recall  f1-score   support

           0       0.97      0.99      0.98      9302
           1       0.97      0.95      0.96      4680

    accuracy                           0.97     13982
   macro avg       0.97      0.97      0.97     13982
weighted avg       0.97      0.97      0.97     13982


Metrics for SVM:
Accuracy: 0.9582, Precision: 0.9770, Recall: 0.9620, F1 Score: 0.9691, Hamming Loss: 0.0068, Micro F1: 0.9696, Macro F1: 0.9733

['/content/drive/.shortcut-targets-by-id/1SLhiH7VulyiPZ7L846kJBEbN1pa4c4zU/Multi_Label_Email_Risk_Detection//reports/svm_predictions.pkl']

####Multi-Layer Perception Model
Activation (Sigmoid)-
$$ σ(z_k) = \frac{1}{1 + e^{-z_k}}$$



Loss Binary Cross Entropy)-
$$Loss = -\sum_{k=1}^{K}[y_k\text{log}(p_k) +(1-y_k)\text{log}(1-p_k)]
$$
Where yk is the ground truth

In [ ]:
# ------------------------------------------------------------
# Convert Sparse Matrix to Dense for Neural Network
# --------------------------------------------------------------
# TensorFlow/Keras Dense layers require dense input.
# Other models (SVM, Logistic Regression) can use sparse matrices.

X_train_dense = X_train.toarray()
X_test_dense = X_test.toarray()

print("Dense training shape:", X_train_dense.shape)
print("Dense testing shape:", X_test_dense.shape)

##Get Input and Output Dimensions
input_shape = X_train_dense.shape[1]
output_shape = len(risk_cols)

##Define Multi-Layer Perceptron Model
MLP_model = models.Sequential([
    layers.Dense(512, activation='relu', input_shape=(input_shape,)),
    layers.Dropout(0.3),  ##Prevent Overfitting
    layers.Dense(256, activation='relu'),
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(output_shape, activation='sigmoid')  ##One probability per risk category
])

##Compile Model
MLP_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
   metrics=['accuracy', tf.keras.metrics.AUC(name='auc')]
)

##Train Model
history = MLP_model.fit(
    X_train_dense,
    Y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

##Predict Risk Probabilities
mlp_probs = MLP_model.predict(X_test_dense)

##Convert Probabilities to Binary Predictions
mlp_preds = (mlp_probs >= 0.4).astype(int)

##Overall Evaluation Metrics
acc = accuracy_score(Y_test, mlp_preds)
prec = precision_score(Y_test, mlp_preds, average='weighted', zero_division=0)
rec = recall_score(Y_test, mlp_preds, average='weighted', zero_division=0)
f1 = f1_score(Y_test, mlp_preds, average='weighted', zero_division=0)
hl = hamming_loss(Y_test, mlp_preds)
micro_f1 = f1_score(Y_test, mlp_preds, average='micro')
macro_f1 = f1_score(Y_test, mlp_preds, average='macro')

##Print Metrics for Each Risk Category
for i, col in enumerate(risk_cols):
    print(f"\n{col}")
    print(classification_report(
            Y_test.iloc[:, i],
            mlp_preds[:, i],
            zero_division=0))

##Store Overall Results
results["NeuralNetwork"] = {
    "accuracy": acc,
    "precision": prec,
    "recall": rec,
    "f1": f1,
    'hamming_loss': hl,
    "micro_f1": micro_f1,
    "macro_f1": macro_f1
    }

##Display Overall Metrics
print("\nMetrics for Neural Network:")
print(f"Accuracy: {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall: {rec:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Hamming Loss: {hl:.4f}")
print(f"Micro F1: {micro_f1:.4f}")
print(f"Macro F1: {macro_f1:.4f}")


# Save the model
os.makedirs(MODELS_DIR, exist_ok=True)

joblib.dump(
    MLP_model,
    f"{MODELS_DIR}/mlp_model.pkl"
)

# Save the predictions
joblib.dump(
    mlp_preds,
    f"{REPORTS_DIR}/mlp_predictions.pkl"
)

Dense training shape: (55928, 10013)
Dense testing shape: (13982, 10013)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 125s 87ms/step - accuracy: 0.7162 - auc: 0.9970 - loss: 0.0355 - val_accuracy: 0.7000 - val_auc: 0.9994 - val_loss: 0.0055
Epoch 2/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 105s 75ms/step - accuracy: 0.7222 - auc: 0.9997 - loss: 0.0036 - val_accuracy: 0.7115 - val_auc: 0.9987 - val_loss: 0.0063
Epoch 3/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 105s 75ms/step - accuracy: 0.7037 - auc: 0.9997 - loss: 0.0022 - val_accuracy: 0.6800 - val_auc: 0.9991 - val_loss: 0.0053
Epoch 4/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 140s 74ms/step - accuracy: 0.7873 - auc: 0.9998 - loss: 0.0013 - val_accuracy: 0.9562 - val_auc: 0.9983 - val_loss: 0.0081
Epoch 5/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 106s 75ms/step - accuracy: 0.7367 - auc: 0.9998 - loss: 0.0013 - val_accuracy: 0.7023 - val_auc: 0.9988 - val_loss: 0.0066
Epoch 6/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 105s 75ms/step - accuracy: 0.7347 - auc: 0.9999 - loss: 7.0896e-04 - val_accuracy: 0.8635 - val_auc: 0.9979 - val_loss: 0.0090
Epoch 7/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 104s 75ms/step - accuracy: 0.7507 - auc: 0.9999 - loss: 7.5898e-04 - val_accuracy: 0.7247 - val_auc: 0.9976 - val_loss: 0.0097
Epoch 8/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 140s 73ms/step - accuracy: 0.7368 - auc: 0.9998 - loss: 0.0011 - val_accuracy: 0.7029 - val_auc: 0.9977 - val_loss: 0.0094
Epoch 9/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 139s 100ms/step - accuracy: 0.7052 - auc: 0.9999 - loss: 5.9564e-04 - val_accuracy: 0.7023 - val_auc: 0.9975 - val_loss: 0.0103
Epoch 10/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 107s 75ms/step - accuracy: 0.7549 - auc: 0.9999 - loss: 6.0104e-04 - val_accuracy: 0.7207 - val_auc: 0.9966 - val_loss: 0.0161
Epoch 11/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 141s 74ms/step - accuracy: 0.7154 - auc: 0.9999 - loss: 0.0013 - val_accuracy: 0.7046 - val_auc: 0.9983 - val_loss: 0.0090
Epoch 12/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 148s 78ms/step - accuracy: 0.7183 - auc: 0.9999 - loss: 8.7201e-04 - val_accuracy: 0.7164 - val_auc: 0.9984 - val_loss: 0.0090
Epoch 13/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 103s 74ms/step - accuracy: 0.7142 - auc: 0.9999 - loss: 4.1236e-04 - val_accuracy: 0.7091 - val_auc: 0.9979 - val_loss: 0.0118
Epoch 14/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 145s 76ms/step - accuracy: 0.7233 - auc: 0.9999 - loss: 5.8766e-04 - val_accuracy: 0.7459 - val_auc: 0.9972 - val_loss: 0.0153
Epoch 15/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 104s 74ms/step - accuracy: 0.7113 - auc: 0.9999 - loss: 0.0013 - val_accuracy: 0.6989 - val_auc: 0.9980 - val_loss: 0.0167
Epoch 16/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 147s 78ms/step - accuracy: 0.7123 - auc: 0.9999 - loss: 4.8676e-04 - val_accuracy: 0.7166 - val_auc: 0.9981 - val_loss: 0.0086
Epoch 17/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 103s 74ms/step - accuracy: 0.7168 - auc: 1.0000 - loss: 3.5419e-04 - val_accuracy: 0.7219 - val_auc: 0.9980 - val_loss: 0.0095
Epoch 18/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 143s 75ms/step - accuracy: 0.7174 - auc: 0.9999 - loss: 4.7907e-04 - val_accuracy: 0.7129 - val_auc: 0.9979 - val_loss: 0.0110
Epoch 19/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 142s 74ms/step - accuracy: 0.7225 - auc: 0.9999 - loss: 5.5905e-04 - val_accuracy: 0.7205 - val_auc: 0.9984 - val_loss: 0.0090
Epoch 20/20
1399/1399 ━━━━━━━━━━━━━━━━━━━━ 147s 78ms/step - accuracy: 0.7208 - auc: 0.9999 - loss: 3.4131e-04 - val_accuracy: 0.7216 - val_auc: 0.9976 - val_loss: 0.0130
437/437 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step

financial_risk
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     13179
           1       0.98      0.93      0.95       803

    accuracy                           0.99     13982
   macro avg       0.99      0.96      0.98     13982
weighted avg       0.99      0.99      0.99     13982


credential_risk
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     13624
           1       1.00      1.00      1.00       358

    accuracy                           1.00     13982
   macro avg       1.00      1.00      1.00     13982
weighted avg       1.00      1.00      1.00     13982


customer_info_risk
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     13622
           1       1.00      1.00      1.00       360

    accuracy                           1.00     13982
   macro avg       1.00      1.00      1.00     13982
weighted avg       1.00      1.00      1.00     13982


proprietary_risk
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     13786
           1       1.00      1.00      1.00       196

    accuracy                           1.00     13982
   macro avg       1.00      1.00      1.00     13982
weighted avg       1.00      1.00      1.00     13982


legal_risk
              precision    recall  f1-score   support

           0       1.00      0.99      1.00      9713
           1       0.99      1.00      0.99      4269

    accuracy                           1.00     13982
   macro avg       0.99      1.00      0.99     13982
weighted avg       1.00      1.00      1.00     13982


attachment_risk
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     13644
           1       1.00      1.00      1.00       338

    accuracy                           1.00     13982
   macro avg       1.00      1.00      1.00     13982
weighted avg       1.00      1.00      1.00     13982


phishing_spam_risk
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9302
           1       0.99      0.99      0.99      4680

    accuracy                           1.00     13982
   macro avg       0.99      1.00      1.00     13982
weighted avg       1.00      1.00      1.00     13982


Metrics for Neural Network:
Accuracy: 0.9911
Precision: 0.9911
Recall: 0.9914
F1 Score: 0.9911
Hamming Loss: 0.0020
Micro F1: 0.9912
Macro F1: 0.9914

['/content/drive/.shortcut-targets-by-id/1SLhiH7VulyiPZ7L846kJBEbN1pa4c4zU/Multi_Label_Email_Risk_Detection//reports/mlp_predictions.pkl']

In [ ]:
# ------------------------------------------------------------
# Faster Exploratory DistilBERT Baseline
# ------------------------------------------------------------
!pip install -q transformers datasets accelerate

import time, torch, joblib
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    DataCollatorWithPadding,
    TrainingArguments,
    Trainer
)

# Recreate source-stratified splits
train_df, test_df = train_test_split(
    combined_df,
    test_size=0.20,
    random_state=26,
    stratify=combined_df["source"]
)

train_df, val_df = train_test_split(
    train_df,
    test_size=0.10,
    random_state=26,
    stratify=train_df["source"]
)

# Use smaller stratified samples for faster exploratory training
def sample_df(df, n):
    if len(df) <= n:
        return df.reset_index(drop=True)

    sample, _ = train_test_split(
        df,
        train_size=n,
        random_state=26,
        stratify=df["source"]
    )
    return sample.reset_index(drop=True)

train_df = sample_df(train_df, 20_000)
val_df = sample_df(val_df, 3_000)

# Create Hugging Face datasets
def make_dataset(df):
    return Dataset.from_dict({
        "text": df["text"].fillna("").astype(str).tolist(),
        "labels": df[risk_cols].astype("float32").values.tolist()
    })

MODEL_NAME = "distilbert-base-uncased"
MAX_LEN = 128
use_gpu = torch.cuda.is_available()

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        max_length=MAX_LEN
    )

train_ds, val_ds, test_ds = [
    make_dataset(df).map(
        tokenize,
        batched=True,
        batch_size=1000,
        remove_columns=["text"]
    )
    for df in (train_df, val_df, test_df)
]

# Load multi-label DistilBERT model
model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=len(risk_cols),
    problem_type="multi_label_classification"
)

# Freeze embeddings and first four transformer layers
for parameter in model.distilbert.embeddings.parameters():
    parameter.requires_grad = False

for layer in model.distilbert.transformer.layer[:4]:
    for parameter in layer.parameters():
        parameter.requires_grad = False

# Evaluation metrics
def compute_metrics(output):
    logits, labels = output
    probs = torch.sigmoid(torch.tensor(logits)).numpy()
    preds = (probs >= 0.50).astype(int)

    return {
        "weighted_f1": f1_score(
            labels, preds, average="weighted", zero_division=0
        ),
        "weighted_recall": recall_score(
            labels, preds, average="weighted", zero_division=0
        ),
        "hamming_loss": hamming_loss(labels, preds)
    }

model_path = f"{MODELS_DIR}/distilbert_email_risk"

args = TrainingArguments(
    output_dir=model_path,
    num_train_epochs=1,
    learning_rate=3e-5,
    per_device_train_batch_size=32 if use_gpu else 8,
    per_device_eval_batch_size=128 if use_gpu else 32,
    eval_strategy="epoch",
    save_strategy="no",
    fp16=use_gpu,
    report_to="none",
    logging_steps=100,
    seed=26
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    processing_class=tokenizer,
    data_collator=DataCollatorWithPadding(tokenizer),
    compute_metrics=compute_metrics
)

# Train model
start = time.perf_counter()
trainer.train()
training_time = time.perf_counter() - start

# Generate test predictions
start = time.perf_counter()
output = trainer.predict(test_ds)
prediction_time = time.perf_counter() - start

probs = torch.sigmoid(
    torch.tensor(output.predictions)
).numpy()

preds = (probs >= 0.50).astype(int)

# Save model and outputs
trainer.save_model(model_path)
tokenizer.save_pretrained(model_path)

joblib.dump(
    preds,
    f"{REPORTS_DIR}/distilbert_predictions.pkl"
)

joblib.dump(
    probs,
    f"{REPORTS_DIR}/distilbert_probabilities.pkl"
)

joblib.dump(
    {
        "Training Time": training_time,
        "Prediction Time": prediction_time,
        "Milliseconds Per Email":
            prediction_time / len(test_ds) * 1000,
        "Training Samples": len(train_ds),
        "Epochs": 1,
        "Maximum Tokens": MAX_LEN
    },
    f"{REPORTS_DIR}/distilbert_efficiency.pkl"
)

print(compute_metrics(
    (output.predictions, output.label_ids)
))
print(f"Training samples: {len(train_ds):,}")
print(f"Training time: {training_time / 60:.2f} minutes")
print(f"Prediction time: {prediction_time:.2f} seconds")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Map:   0%|          | 0/20000 [00:00<?, ? examples/s]

Map:   0%|          | 0/3000 [00:00<?, ? examples/s]

Map:   0%|          | 0/13982 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'weighted_f1': 0.9947512161806572, 'weighted_recall': 0.992635694154014, 'hamming_loss': 0.0011749800764247911}
Training samples: 20,000
Training time: 126.04 minutes
Prediction time: 2732.74 seconds